name: PR Branch Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-target-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check target branch
        id: check-branch
        run: |
          if [ "${{ github.event.pull_request.base.ref }}" != "develop" ]; then
            echo "PR is not targeting 'develop' branch. Closing PR."
            echo "::set-output name=should_close::true"
          else
            echo "PR is targeting 'develop' branch. All good."
            echo "::set-output name=should_close::false"
          fi

      - name: Close PR if not targeting develop
        if: steps.check-branch.outputs.should_close == 'true'
        uses: superbrothers/close-pull-request@v3
        with:
          comment: "请推送到 `develop` 分支。当前 PR 的目标分支不正确，已关闭。"
